### PR TITLE
Fixing all versions of actor prover dependencies, so it will work on …

### LINKED ISSUE #33: Fix proof-generator-multithreaded binary dependencies
Currently, proof-generator-multithreaded from the deb package has three following dependencies:
`libhwloc-dev`, `libyaml-cpp-dev`, `libfmt-dev`

It results in getting this error when trying to run the binary:
```bash
proof-generator-multithreaded: /opt/boost/boost/include/boost/container/pmr/polymorphic_allocator.hpp:58: boost::container::pmr::polymorphic_allocator<T>::polymorphic_allocator(boost::container::pmr::memory_resource*) [with T = char]: Assertion `r != 0' failed.
Aborted (core dumped)
```

Tested by installing the `proof-producer` deb package version 0.1.3 with -DBUILD_WITH_BOOST_STATIC_LIBS=True on:
* Ubuntu 22.04 Docker image
* Ubuntu 22.04 cpx21 hetzner server (3 vcpu, 4GB RAM)
* Ubuntu 22.04 cpx51 hetzner server (16 vcpu, 32GB RAM)

If built from source, it works on Ubuntu 22.04 cpx51 hetzner server (16 vcpu, 32GB RAM), so there probably is a problem with the libraries versions being used by the multithreaded version.

### PR DESCRIPTION
**Pull request by martun**
…all systems.

### CODE REVIEW

File: bin/proof-generator-multithreaded/include/nil/proof-generator-multithreaded/aspects/prover_vanilla.hpp [hunk 1]
```diff
@@ -59,13 +59,16 @@ namespace nil {
...
+                int get_shard0_mem_scale() const;
+
             protected:
                 boost::shared_ptr<path> path_aspect;
 
                 boost::filesystem::path circuit_file_path;
                 boost::filesystem::path assignment_table_file_path;
                 boost::filesystem::path proof_file_path;
-                bool skip_verification;
+                bool skip_verification = false;
```
Comment (martun) [inline bin/proof-generator-multithreaded/include/nil/proof-generator-multithreaded/aspects/prover_vanilla.hpp]: We need false here, otherwise it defaulted to a value of 170, which is "true".

File: bin/proof-generator-multithreaded/src/main.cpp [hunk 2]
```diff
@@ -137,10 +137,11 @@ struct prover {
             context_.find<nil::proof_generator::aspects::prover_vanilla>()->input_assignment_file_path();
 
         skip_verification = context_.find<nil::proof_generator::aspects::prover_vanilla>()->is_skip_verification_mode_on();
+        shard0_mem_scale = context_.find<nil::proof_generator::aspects::prover_vanilla>()->get_shard0_mem_scale();
 
         proof_file = context_.find<nil::proof_generator::aspects::prover_vanilla>()->output_proof_file_path();
 
-        std::vector<std::string> arguments = { "program_name", "--shard0-mem-scale", "4800" };
+        std::vector<std::string> arguments = { "Program_name", "--shard0-mem-scale", std::to_string(shard0_mem_scale) };
```
Comment (martun) [inline bin/proof-generator-multithreaded/src/main.cpp]: We don't care about the program name here, it's not used anyway, so just kept this fake parameter here.

File: VERSION [hunk 3]
```diff
@@ -1 +1 @@
-0.1.1
\ No newline at end of file
+0.1.4
```
Comment (nkaskov) [inline VERSION]: Do you know if we still need the VERSION file? I thought we could delete it, since the versions come from the git tags+git describe hashes

File: README.md [hunk 4]
```diff
@@ -40,7 +40,7 @@ ${ZKLLVM_BUILD:-build}/bin/assigner/assigner -b ${ZKLLVM_BUILD:-build}/examples/
 
     Install fmt-6
     ```
-    wget http://launchpadlibrarian.net/466750967/libfmt-dev_6.1.2+ds-2_amd64.deb
+    wget http://archive.ubuntu.com/ubuntu/pool/universe/f/fmtlib/libfmt-dev_6.1.2
```
Comment (nkaskov) [inline README.md]: But the installation through apt install does not require it, right? I mean, apt should automatically install all the dependencies.

File: CMakeLists.txt [hunk 5]
```diff
@@ -96,7 +96,8 @@ set(CPACK_GENERATOR DEB)
 set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
 set(CPACK_DEBIAN_PACKAGE_MAINTAINER "=nil; Foundation")
 
-set(CPACK_DEBIAN_PACKAGE_DEPENDENCIES_MULTITHREADED_VERSION "libhwloc-dev, libyaml-cpp-dev, libfmt-dev")
+set(CPACK_DEBIAN_PACKAGE_DEPENDENCIES_MULTITHREADED_VERSION "libhwloc-dev (=2.7.0-2ubuntu1), libyaml-cpp-dev (=0.7.0+dfsg-8build1), libfmt-dev(=6.1.2+ds-2), libc-dev, lksctp-tools, libatomic1, libprotobuf-dev (=3.12.4-1ubuntu7.22.04.1), liblz4-dev (=1.9.3-2build2), libgnutls28-dev (=3.7.3-4ubuntu1.3), libc-ares-dev (=1.18.1-1ubuntu0.22.04.2)")
```
Comment (nkaskov) [inline CMakeLists.txt]: Do we need all the list or can we drop some dependencies? This is a really long list we have here.

File: README.md (hunk 4 above)
Comment (martun) [reply README.md]: Nope, apt will not find version 6, because it's too old for Ubuntu 22.04, apt will see only versions 8+. I can add an old repository before "apt update", but I think it's better to manually download this single package, than adding an old repo to sources list.

File: CMakeLists.txt (hunk 5 above)
Comment (martun) [reply CMakeLists.txt]: It's safer this way. In theory, all of these can be used by actor. We can remove things like libc-dev and libatomic1, because they will be on the system for sure, but it's safer to keep them.

File: VERSION (hunk 3 above)
Comment (martun) [reply VERSION]: Looks like we don't need it. Here's how the version string is created:

echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

I deleted it, if something fails we will recover.

Comment (nkaskov) [reply VERSION]: I agree.

File: README.md (hunk 4 above)
Comment (nkaskov) [reply README.md]: Can't we use a newer version?

File: CMakeLists.txt (hunk 5 above)
Comment (nkaskov) [reply CMakeLists.txt]: Alright, let's review it latter.

File: README.md (hunk 4 above)
Comment (martun) [reply README.md]: Nope, we have copied the code of seastar, we will need to update it, it's long...

Comment (x-mass) [reply README.md]: Builds and produces the proof just fine inside clean ubuntu:22.04 with fmt of version 8.1.1

**Review by x-mass — APPROVED** [review]
I've built it inside GH runner container, then tested on clean ubuntu:22.04, on research server. Everywhere proof was generated
